version: '3.3'
services:
  sodspringbootapp01:
    image: sodminiproject01:latest
    container_name: sodminiproject01-app
    depends_on:
      - sodmariadb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mystudentsdb:3306/sod_projectmin1?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    ports:
      - 8088:8088
    command: >
      /bin/bash -c "
              while ! nc -z mystudentsdb 3306;
              do
                echo sleeping;
                sleep 1;
              done;
              echo Connected!;
            "
  sodmariadb:
    image: mariadb:latest
    container_name: mystudentsdb
    volumes:
      - my-db:/var/lib/mysql/
    environment:
      - MYSQL_ROOT_PASSWORD=rootPassword
      - MYSQL_DATABASE=sod_projectmin1
      - MYSQL_USER=sod
      - MYSQL_PASSWORD=ThePassword
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8
  # Names our volume
volumes:
    my-db: